import {useEffect,useState} from 'react';
import {Link,useNavigate} from 'react-router-dom';
import {useAuth} from '../auth';
import {api} from '../api';
export function Dashboard(){const {user,logout}=useAuth();if(user.role==='volunteer')return <VolunteerHome user={user} logout={logout}/>;if(user.role==='admin')return <AdminHome user={user} logout={logout}/>;return <ParticipantHome user={user} logout={logout}/>;}
function Header({label,user,logout}){return <header><div><p className="eyebrow">{label}</p><h1>Welcome, {user.name}</h1></div><button className="secondary compact" onClick={logout}>LOG OUT</button></header>}
function ParticipantHome({user,logout}){const [tag,setTag]=useState(undefined);useEffect(()=>{api('/api/nfc/my-tag').then(r=>setTag(r.tag)).catch(()=>setTag(null));},[]);return <main className="shell"><Header label="PLAYER HUB" user={user} logout={logout}/><section className="hero"><span className="badge">{user.participantId}</span><h2>Your CodeRed journey starts here.</h2><p>Complete your profile, meet participants, and earn XP through verified team challenges.</p></section><section className="grid"><Link className="action-card" to="/profile"><strong>Player profile</strong><span>Edit your public links and identity →</span></Link>{tag?<a className="action-card" href={tag.url}><strong>NFC badge</strong><span>Open your programmed badge link →</span></a>:<div className="action-card disabled"><strong>NFC badge</strong><span>{tag===undefined?'Checking badge…':'Ask an admin to issue your tag'}</span></div>}<Link className="action-card" to="/network"><strong>Network</strong><span>Connections and profile views →</span></Link><Link className="action-card" to="/quests"><strong>Quest town</strong><span>Complete challenges and submit proof →</span></Link></section></main>}
function VolunteerHome({user,logout}){const navigate=useNavigate();const [badge,setBadge]=useState('');const [error,setError]=useState('');function open(e){e.preventDefault();setError('');try{const url=new URL(badge);const match=url.pathname.match(/^\/nfc\/t\/([A-Za-z0-9_-]{32})$/);if(match)return navigate(`/volunteer/nfc/${match[1]}`);}catch{}const token=badge.trim();if(/^[A-Za-z0-9_-]{32}$/.test(token))return navigate(`/volunteer/nfc/${token}`);setError('Enter a valid CodeRed NFC badge URL or token.');}return <main className="shell"><Header label="VOLUNTEER DESK" user={user} logout={logout}/><section className="grid"><section className="panel"><h2>Scan a participant badge</h2><p>Tap their NFC badge with this phone, or paste its URL below.</p><form onSubmit={open}><label>Badge URL or token<input value={badge} onChange={e=>setBadge(e.target.value)} required/></label>{error&&<p className="error">{error}</p>}<button>OPEN RESOURCE DESK</button></form></section><Link className="action-card" to="/volunteer/quests"><strong>Quest verification</strong><span>Review participant proof and award XP →</span></Link></section></main>}
function AdminHome({user,logout}){return <main className="shell"><Header label="ADMIN CONSOLE" user={user} logout={logout}/><section className="grid"><Link className="action-card" to="/volunteer/quests"><strong>Quest verification</strong><span>Review the shared proof queue →</span></Link><div className="action-card disabled"><strong>NFC administration</strong><span>Next admin tool being migrated</span></div></section></main>}
