'use client'

import { useEffect, useMemo, useState } from 'react'
import QRCodeSVG from 'react-qr-code'
import { Check, Copy, Nfc, Search } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'

type Participant={_id:string;name:string;email:string;teamId?:string}
type Issued={url:string;token:string;warning:string;participant:{name:string;participant_id:string};tag:{token_hint:string}}

export default function NfcTagAdminPage(){
  const[participants,setParticipants]=useState<Participant[]>([]);const[query,setQuery]=useState('');const[selected,setSelected]=useState<Participant|null>(null);const[issued,setIssued]=useState<Issued|null>(null);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[copied,setCopied]=useState(false)
  useEffect(()=>{fetch('/api/admin/participants').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message);setParticipants(d.participants||[])}).catch(e=>setError(e.message||'Could not load participants.'))},[])
  const matches=useMemo(()=>{const needle=query.toLowerCase().trim();if(!needle)return[];return participants.filter(p=>`${p.name} ${p.email} ${p.teamId||''}`.toLowerCase().includes(needle)).slice(0,8)},[participants,query])
  async function issue(){if(!selected)return;setBusy(true);setError('');setIssued(null);const response=await fetch('/api/admin/nfc/tags/issue',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({participantId:selected._id})});const body=await response.json();setBusy(false);if(!response.ok)return setError(body.message||'Could not issue tag.');setIssued(body)}
  async function copy(){if(!issued)return;await navigator.clipboard.writeText(issued.url);setCopied(true);setTimeout(()=>setCopied(false),1500)}
  return <div className="space-y-6 max-w-5xl"><div><h1 className="text-3xl font-bold text-primary flex items-center gap-3"><Nfc/> NFC Badge Station</h1><p className="text-muted-foreground mt-1">Issue one secure tag URL, program it, then verify it on a phone before moving on.</p></div><div className="grid lg:grid-cols-2 gap-6"><Card><CardHeader><CardTitle>1. Select participant</CardTitle><CardDescription>Search by name, email or team.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={query} onChange={e=>{setQuery(e.target.value);setSelected(null);setIssued(null)}} placeholder="Search participant..."/></div>{matches.length>0&&<div className="border rounded-md divide-y">{matches.map(p=><button key={p._id} onClick={()=>{setSelected(p);setQuery(p.name)}} className={`w-full text-left p-3 hover:bg-secondary ${selected?._id===p._id?'bg-primary/10':''}`}><b className="block">{p.name}</b><span className="text-xs text-muted-foreground">{p.teamId||'No team'} · {p.email}</span></button>)}</div>}<Button onClick={issue} disabled={!selected||busy} className="w-full"><Nfc className="mr-2 h-4 w-4"/>{busy?'ISSUING...':'ISSUE NFC TAG'}</Button>{error&&<p className="text-sm text-destructive" role="alert">{error}</p>}</CardContent></Card><Card><CardHeader><CardTitle>2. Program and verify</CardTitle><CardDescription>The raw URL appears once. Do not leave this screen until the physical tag is verified.</CardDescription></CardHeader><CardContent>{issued?<div className="space-y-4 text-center"><div className="bg-white p-4 inline-block border"><QRCodeSVG value={issued.url} size={190}/></div><div><b className="block text-lg">{issued.participant.name}</b><span className="font-mono text-xs">Tag hint: {issued.tag.token_hint}</span></div><div className="flex gap-2"><Input readOnly value={issued.url} className="font-mono text-xs"/><Button variant="outline" onClick={copy}>{copied?<Check/>:<Copy/>}</Button></div><ol className="text-left text-sm space-y-2 list-decimal pl-5"><li>Write this URL as the first NDEF URI record.</li><li>Tap the tag with an iPhone and confirm this participant opens.</li><li>Print the QR above as the badge fallback.</li><li>Only then lock the physical tag.</li></ol></div>:<div className="min-h-72 grid place-items-center text-center text-muted-foreground"><div><Nfc className="mx-auto h-12 w-12 mb-3 opacity-40"/><p>Select a participant and issue a tag.</p></div></div>}</CardContent></Card></div></div>
}

