'use client'
import { FormEvent, useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowLeft, ArrowRight, Check, Github, Linkedin, Link as LinkIcon } from 'lucide-react'
import { AVATARS } from '@/lib/game'
import { PixelAvatar } from '@/components/game/PixelAvatar'
import { useAuth } from '@/contexts/AuthContext'
export default function OnboardingPage() {
  const router = useRouter(); const { refreshUser } = useAuth(); const [step, setStep] = useState(0); const [saving, setSaving] = useState(false); const [error, setError] = useState(''); const [form, setForm] = useState({ username: '', bio: '', github: '', linkedin: '', portfolio: '', avatarKey: 'byte' })
  useEffect(() => { fetch('/api/participant/profile').then((r) => r.json()).then(({ profile }) => { if (!profile) return; setForm((f) => ({ ...f, username: profile.username || '', bio: profile.bio || '', github: profile.github_profile || '', linkedin: profile.linkedin_url || '', portfolio: profile.portfolio_url || '', avatarKey: profile.avatar_key || 'byte' })); if (profile.onboarding_completed && !profile.github_profile && !profile.linkedin_url && !profile.portfolio_url) setStep(2) }) }, [])
  const set = (key: string, value: string) => setForm((current) => ({ ...current, [key]: value }))
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(''); const response = await fetch('/api/participant/profile', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) { setSaving(false); return setError(data.message || 'Could not save profile.') }; await refreshUser(); router.replace(`/p/${form.username.toLowerCase()}`) }
  return <div className="onboarding-wrap pixel-panel"><div className="onboarding-progress">{['AVATAR', 'IDENTITY', 'SOCIAL LINKS'].map((label, index) => <span className={index <= step ? 'done' : ''} key={label}><i>{index < step ? <Check/> : index + 1}</i>{label}</span>)}</div><form onSubmit={submit}>
    {step === 0 && <section><p className="eyebrow">NEW SAVE FILE</p><h1>Choose your player</h1><p className="muted-game">You can change this later.</p><div className="avatar-picker">{AVATARS.map((avatar) => <button type="button" className={form.avatarKey === avatar.key ? 'selected' : ''} onClick={() => set('avatarKey', avatar.key)} key={avatar.key}><PixelAvatar avatarKey={avatar.key} size="lg"/><b>{avatar.name}</b></button>)}</div></section>}
    {step === 1 && <section><p className="eyebrow">PLAYER PROFILE</p><h1>Name your character</h1><label className="game-field">UNIQUE HANDLE<input required pattern="[a-zA-Z0-9_]{3,24}" value={form.username} onChange={(e) => set('username', e.target.value)} placeholder="pixel_pirate"/></label><label className="game-field">SHORT BIO<textarea maxLength={180} value={form.bio} onChange={(e) => set('bio', e.target.value)} placeholder="Builder, designer, midnight debugger..."/></label></section>}
    {step === 2 && <section><p className="eyebrow">STEP 3 OF 3 · REQUIRED</p><h1>Add your social links</h1><p className="muted-game">GitHub, LinkedIn, and your portfolio become buttons on your scannable Linktree-style card.</p><div className="social-onboarding"><label className="game-field icon-field"><Github/> GITHUB PROFILE<input type="url" value={form.github} onChange={(e) => set('github', e.target.value)} placeholder="https://github.com/you"/></label><label className="game-field icon-field"><Linkedin/> LINKEDIN PROFILE<input type="url" value={form.linkedin} onChange={(e) => set('linkedin', e.target.value)} placeholder="https://linkedin.com/in/you"/></label><label className="game-field icon-field"><LinkIcon/> PORTFOLIO / RESUME<input type="url" value={form.portfolio} onChange={(e) => set('portfolio', e.target.value)} placeholder="https://your.site"/></label></div><p className="network-tip">REQUIRED: Add at least one link. You can add or update the others later.</p>{error && <p className="game-error">{error}</p>}</section>}
    <div className="onboarding-actions">{step > 0 && <button type="button" className="pixel-button secondary" onClick={() => setStep(step - 1)}><ArrowLeft/> BACK</button>}{step < 2 ? <button type="button" className="pixel-button" onClick={() => setStep(step + 1)}>CONTINUE <ArrowRight/></button> : <button className="pixel-button" disabled={saving}>{saving ? 'SAVING...' : 'CREATE PLAYER CARD'} <Check/></button>}</div>
  </form></div>
}
