'use client'
import { FormEvent, useEffect, useMemo, useState } from 'react'
import { Camera, Check, Clock3, Code2, Flag, Handshake, LockKeyhole, MapPin, RefreshCw, ScrollText, Send, Sparkles, Star, Trophy, X } from 'lucide-react'
import { PixelTownGame } from '../../../components/game/PixelTownGame'

type Quest={id:string;title:string;description:string;points:number;category:string;proof_type:string;submission:null|{status:'pending'|'approved'|'rejected';review_note?:string}}
const categoryIcon:any={technical:Code2,social:Handshake,general:Star,fun:Sparkles}
const positions=[{left:'15%',top:'73%'},{left:'31%',top:'57%'},{left:'52%',top:'63%'},{left:'76%',top:'50%'},{left:'84%',top:'25%'},{left:'60%',top:'29%'}]

export default function QuestsPage(){
  const[quests,setQuests]=useState<Quest[]>([]);const[focused,setFocused]=useState<Quest|null>(null);const[submitQuest,setSubmitQuest]=useState<Quest|null>(null);const[proofText,setProofText]=useState('');const[proof,setProof]=useState<File|null>(null);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');const[loadError,setLoadError]=useState('');const[loading,setLoading]=useState(true);const[player,setPlayer]=useState({x:11,y:83});const[direction,setDirection]=useState('down')
  const load=()=>{setLoading(true);setLoadError('');fetch('/api/quests').then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.message);setQuests(d.quests||[])}).catch(e=>setLoadError(e.message||'Could not load quests.')).finally(()=>setLoading(false))};useEffect(load,[])
  useEffect(()=>{try{const saved=window.localStorage.getItem('codered:quest-player-position');if(saved){const parsed=JSON.parse(saved);if(typeof parsed.x==='number'&&typeof parsed.y==='number')setPlayer({x:parsed.x,y:parsed.y})}}catch{/* Position restore is optional. */}},[])
  useEffect(()=>{try{window.localStorage.setItem('codered:quest-player-position',JSON.stringify(player))}catch{/* Position persistence is optional. */}},[player])
  const blockedZones=[{x1:42,x2:61,y1:48,y2:64},{x1:22,x2:38,y1:34,y2:50},{x1:72,x2:91,y1:7,y2:26},{x1:76,x2:94,y1:43,y2:61},{x1:7,x2:25,y1:55,y2:73}]
  const step=(x:number,y:number,d:string)=>{setDirection(d);setPlayer(current=>{const next={x:Math.max(5,Math.min(95,current.x+x)),y:Math.max(9,Math.min(91,current.y+y))};const blocked=blockedZones.some(zone=>next.x>zone.x1&&next.x<zone.x2&&next.y>zone.y1&&next.y<zone.y2);return blocked?current:next})}
  const completed=quests.filter(q=>q.submission?.status==='approved').length;const points=quests.reduce((sum,q)=>sum+(q.submission?.status==='approved'?q.points:0),0)
  const firstOpen=useMemo(()=>{const index=quests.findIndex(q=>q.submission?.status!=='approved');return index<0?quests.length:index},[quests])
  const stateFor=(quest:Quest,index:number)=>quest.submission?.status==='approved'?'complete':quest.submission?.status==='pending'?'pending':index>firstOpen?'locked':'current'
  const interact=()=>{const nearest=quests.map((quest,index)=>({quest,index,distance:Math.hypot(player.x-parseFloat(positions[index]?.left||'0'),player.y-parseFloat(positions[index]?.top||'0'))})).filter(item=>item.index<positions.length&&item.distance<15&&!['complete','pending','locked'].includes(stateFor(item.quest,item.index))).sort((a,b)=>a.distance-b.distance)[0];if(nearest)setFocused(nearest.quest)}
  const nearbyQuest=quests.map((quest,index)=>({quest,index,distance:Math.hypot(player.x-parseFloat(positions[index]?.left||'0'),player.y-parseFloat(positions[index]?.top||'0'))})).filter(item=>item.index<positions.length&&item.distance<15&&stateFor(item.quest,item.index)==='current').sort((a,b)=>a.distance-b.distance)[0]?.quest
  useEffect(()=>{const move=(event:KeyboardEvent)=>{const key=event.key.toLowerCase();if((key==='e'||key==='enter')&&!focused&&!submitQuest){event.preventDefault();interact();return}const vectors:any={arrowup:[0,-2,'up'],w:[0,-2,'up'],arrowdown:[0,2,'down'],s:[0,2,'down'],arrowleft:[-2,0,'left'],a:[-2,0,'left'],arrowright:[2,0,'right'],d:[2,0,'right']};const vector=vectors[key];if(!vector||focused||submitQuest)return;event.preventDefault();step(vector[0],vector[1],vector[2])};window.addEventListener('keydown',move);return()=>window.removeEventListener('keydown',move)},[focused,submitQuest,quests,player])
  const walk=(x:number,y:number,d:string)=>step(x,y,d)
  async function submit(event:FormEvent){event.preventDefault();if(!submitQuest)return;setBusy(true);setMessage('');const form=new FormData();form.set('taskId',submitQuest.id);form.set('proofText',proofText);if(proof)form.set('proof',proof);const response=await fetch('/api/quests/submit',{method:'POST',body:form});const data=await response.json();setBusy(false);if(!response.ok)return setMessage(data.message);setSubmitQuest(null);setFocused(null);setProof(null);setProofText('');load()}
  return <div className="quest-world-page">
    <header className="quest-map-header"><div><p className="eyebrow"><MapPin/> CODERED CAMPUS</p><h1>Adventure map</h1><p>Clear each checkpoint to unlock the next quest.</p></div><div className="map-hud"><span><Trophy/> <b>{points}</b> XP</span><span><Flag/> <b>{completed}</b> / {quests.length}</span></div></header>
    {loadError?<div className="pixel-panel empty-game"><b>MAP COULD NOT LOAD</b><p>{loadError}</p><button className="pixel-button" onClick={load}><RefreshCw/> TRY AGAIN</button></div>:loading?<div className="pixel-panel empty-game"><RefreshCw className="spin"/><b>DRAWING MAP...</b></div>:<>
      <PixelTownGame quests={quests} states={quests.map((quest,index)=>stateFor(quest,index))} onInteract={quest=>setFocused(quests.find(item=>item.id===quest.id)||null)}/>
      <section className="quest-overworld pixel-panel" aria-label="Quest adventure map">
        <div className="map-vignette"/><div className="map-start"><Flag/> START</div><div className="map-finish"><Trophy/> FINISH</div><div className={`quest-player facing-${direction}`} style={{left:`${player.x}%`,top:`${player.y}%`}} aria-label="Your avatar"><span>🧢</span><b>YOU</b></div>{nearbyQuest&&<button className="nearby-prompt" onClick={interact}>E <span>TALK TO {nearbyQuest.title.toUpperCase()}</span></button>}<div className="map-controls" aria-label="Movement controls"><button onClick={()=>walk(0,-2,'up')} aria-label="Move up">▲</button><div><button onClick={()=>walk(-2,0,'left')} aria-label="Move left">◀</button><button onClick={()=>walk(0,2,'down')} aria-label="Move down">▼</button><button onClick={()=>walk(2,0,'right')} aria-label="Move right">▶</button></div><button className="map-interact" onClick={interact} aria-label="Interact with nearby task">A</button></div><div className="map-instruction">WASD / ARROWS TO WALK · E / ENTER TO INTERACT</div>
        {quests.slice(0,6).map((quest,index)=>{const state=stateFor(quest,index);const Icon=categoryIcon[quest.category]||Star;return <button key={quest.id} style={positions[index]} className={`map-node ${state}`} disabled={state==='locked'} onClick={()=>setFocused(quest)} aria-label={`${quest.title}, ${state}`}><span className="node-pulse"/><i>{state==='complete'?<Check/>:state==='pending'?<Clock3/>:state==='locked'?<LockKeyhole/>:<Icon/>}</i><b>STEP {index+1}</b><em>{quest.title}</em></button>})}
        {focused&&(()=>{const index=quests.findIndex(q=>q.id===focused.id);const state=stateFor(focused,index);const Icon=categoryIcon[focused.category]||Star;return <aside className="map-quest-card"><button className="map-card-close" onClick={()=>setFocused(null)}><X/></button><div className="map-card-top"><i><Icon/></i><span>{focused.category}<b>+{focused.points} XP</b></span></div><h2>{focused.title}</h2><p>{focused.description}</p>{focused.submission?.review_note&&<div className="review-message">VOLUNTEER: {focused.submission.review_note}</div>}{state==='complete'?<div className="map-cleared"><Check/> QUEST CLEARED</div>:state==='pending'?<div className="map-waiting"><Clock3/> PROOF UNDER REVIEW</div>:<button className="pixel-button" onClick={()=>setSubmitQuest(focused)}>START QUEST <Send/></button>}</aside>})()}
      </section>
      <section className="quest-route pixel-panel"><div className="route-title"><ScrollText/> QUEST ROUTE</div>{quests.map((quest,index)=>{const state=stateFor(quest,index);return <button key={quest.id} disabled={state==='locked'} onClick={()=>setFocused(quest)} className={state}><i>{state==='complete'?<Check/>:state==='pending'?<Clock3/>:state==='locked'?<LockKeyhole/>:index+1}</i><span><b>{quest.title}</b><small>{state==='locked'?'Clear the previous checkpoint':state==='current'?'Available now':state==='pending'?'Volunteer is checking proof':'Complete'}</small></span><strong>+{quest.points}</strong></button>})}</section>
    </>}
    {submitQuest&&<div className="game-modal" role="dialog" aria-modal="true"><form className="pixel-panel proof-dialog" onSubmit={submit}><button type="button" className="modal-close" onClick={()=>setSubmitQuest(null)}><X/></button><p className="eyebrow">CHECKPOINT PROOF</p><h2>{submitQuest.title}</h2>{submitQuest.proof_type==='image'?<label className="proof-drop"><Camera/><b>{proof?proof.name:'CHOOSE SCREENSHOT OR PHOTO'}</b><span>JPG, PNG or WebP · max 2 MB</span><input type="file" required accept="image/jpeg,image/png,image/webp" onChange={e=>setProof(e.target.files?.[0]||null)}/></label>:<label className="game-field">{submitQuest.proof_type==='link'?'PROOF LINK':'YOUR NOTE'}<textarea required value={proofText} onChange={e=>setProofText(e.target.value)} placeholder={submitQuest.proof_type==='link'?'https://github.com/...':'What did you learn?'}/></label>}{message&&<p className="game-error">{message}</p>}<button className="pixel-button" disabled={busy}>{busy?'UPLOADING...':'SEND TO VOLUNTEER'} <Send/></button></form></div>}
  </div>
}
