'use client'
import { FormEvent, useEffect, useRef, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Camera, Keyboard, ScanLine, Users, X } from 'lucide-react'

function usernameFrom(value:string){try{const url=new URL(value);const match=url.pathname.match(/^\/p\/([^/]+)/);return match?.[1]||null}catch{return value.trim().replace(/^@/,'')||null}}
export default function NetworkScannerPage(){
  const router=useRouter();const scanner=useRef<any>(null);const runningScanners=useRef(new Set<any>());const handled=useRef(false);const [manual,setManual]=useState('');const [error,setError]=useState('');const [cameraError,setCameraError]=useState('');
  async function stopScanner(instance=scanner.current){if(!instance||!runningScanners.current.has(instance))return;runningScanners.current.delete(instance);try{await instance.stop()}catch{/* Scanner may already have been released during navigation. */}}
  async function connect(raw:string){if(handled.current)return;const username=usernameFrom(raw);if(!username)return setError('That is not a CODERED player QR.');handled.current=true;setError('');const response=await fetch(`/api/profiles/${encodeURIComponent(username)}/scan`,{method:'POST'});const data=await response.json();if(!response.ok){handled.current=false;return setError(data.message||'Could not connect.')}await stopScanner();router.push(`/p/${username}`)}
  useEffect(()=>{let active=true;let instance:any=null;let starting:Promise<void>|null=null;import('html5-qrcode').then(({Html5Qrcode})=>{if(!active)return;instance=new Html5Qrcode('network-qr-reader');scanner.current=instance;starting=instance.start({facingMode:'environment'},{fps:8,qrbox:{width:230,height:230}},connect,()=>{}).then(async()=>{runningScanners.current.add(instance);if(!active)await stopScanner(instance)}).catch(()=>{if(active)setCameraError('Camera unavailable. Allow camera access or enter a username below.')})});return()=>{active=false;if(starting)void starting.then(()=>stopScanner(instance));else if(instance)void stopScanner(instance)}},[])
  function submit(e:FormEvent){e.preventDefault();connect(manual)}
  return <div className="game-stack network-scan-page"><div className="page-heading"><div><p className="eyebrow">SOCIAL QUEST</p><h1>Scan a player</h1><p>Point the camera at another participant’s networking QR to exchange profiles.</p></div><ScanLine className="heading-icon"/></div><div className="network-scan-grid"><section className="pixel-panel scanner-console"><div className="scanner-label"><Camera/> LIVE SCANNER</div><div id="network-qr-reader"/><div className="scan-reticle" aria-hidden><i/><i/><i/><i/></div>{cameraError&&<p className="game-error">{cameraError}</p>}</section><section className="pixel-panel scan-help"><Users/><h2>Meet. Scan. Connect.</h2><p>A successful scan adds one connection to both participants’ networking stats. Repeated scans do not inflate the count.</p><ol><li>Ask them to open Player Card</li><li>Scan their networking QR</li><li>Open GitHub, LinkedIn or portfolio</li></ol><form onSubmit={submit}><label className="game-field"><Keyboard/> ENTER HANDLE INSTEAD<input value={manual} onChange={e=>setManual(e.target.value)} placeholder="@pixel_pirate" required/></label>{error&&<p className="game-error"><X/> {error}</p>}<button className="pixel-button">CONNECT <ScanLine/></button></form></section></div></div>
}
