'use client'
import { FormEvent, useEffect, useRef, useState } from 'react'
import { useRouter } from 'next/navigation'
import { Camera, Keyboard, ScanLine, Users, X } from 'lucide-react'

function scanTarget(value:string){try{const url=new URL(value);const nfc=url.pathname.match(/^\/nfc\/t\/([A-Za-z0-9_-]{32})$/);if(nfc)return{kind:'nfc' as const,value:nfc[1]};const profile=url.pathname.match(/^\/p\/([^/]+)/);return profile?{kind:'profile' as const,value:profile[1]}:null}catch{const username=value.trim().replace(/^@/,'');return username?{kind:'profile' as const,value:username}:null}}
export default function NetworkScannerPage(){
  const router=useRouter();const scanner=useRef<any>(null);const runningScanners=useRef(new Set<any>());const handled=useRef(false);const [manual,setManual]=useState('');const [error,setError]=useState('');const [cameraError,setCameraError]=useState('');
  async function stopScanner(instance=scanner.current){if(!instance||!runningScanners.current.has(instance))return;runningScanners.current.delete(instance);try{await instance.stop()}catch{/* Scanner may already have been released during navigation. */}}
  async function connect(raw:string){if(handled.current)return;const target=scanTarget(raw);if(!target)return setError('That is not a CODERED badge or player QR.');handled.current=true;setError('');if(target.kind==='nfc'){await stopScanner();router.push(`/nfc/t/${target.value}`);return}const response=await fetch(`/api/profiles/${encodeURIComponent(target.value)}/scan`,{method:'POST'});const data=await response.json();if(!response.ok){handled.current=false;return setError(data.message||'Could not connect.')}await stopScanner();router.push(`/p/${target.value}`)}
  useEffect(()=>{let active=true;let instance:any=null;let starting:Promise<void>|null=null;import('html5-qrcode').then(({Html5Qrcode})=>{if(!active)return;instance=new Html5Qrcode('network-qr-reader');scanner.current=instance;starting=instance.start({facingMode:'environment'},{fps:8,qrbox:{width:230,height:230}},connect,()=>{}).then(async()=>{runningScanners.current.add(instance);if(!active)await stopScanner(instance)}).catch(()=>{if(active)setCameraError('Camera unavailable. Allow camera access or enter a username below.')})});return()=>{active=false;if(starting)void starting.then(()=>stopScanner(instance));else if(instance)void stopScanner(instance)}},[])
  function submit(e:FormEvent){e.preventDefault();connect(manual)}
  return <div className="game-stack network-scan-page"><div className="page-heading"><div><p className="eyebrow">SOCIAL QUEST · NFC PRIMARY</p><h1>Tap a player badge</h1><p>Hold your phone near their NFC badge. Use the camera below for the backup QR.</p></div><ScanLine className="heading-icon"/></div><div className="network-scan-grid"><section className="pixel-panel scanner-console"><div className="scanner-label"><Camera/> BACKUP QR SCANNER</div><div id="network-qr-reader"/><div className="scan-reticle" aria-hidden><i/><i/><i/><i/></div>{cameraError&&<p className="game-error">{cameraError}</p>}</section><section className="pixel-panel scan-help"><Users/><h2>Tap. Confirm. Connect.</h2><p>NFC opens the player’s secure badge page in Safari. The QR backup follows the exact same route.</p><ol><li>Hold the top of your phone near their badge</li><li>Tap the NFC notification</li><li>Confirm their profile and connect</li></ol><form onSubmit={submit}><label className="game-field"><Keyboard/> ENTER HANDLE OR BADGE URL<input value={manual} onChange={e=>setManual(e.target.value)} placeholder="@pixel_pirate" required/></label>{error&&<p className="game-error"><X/> {error}</p>}<button className="pixel-button">OPEN PROFILE <ScanLine/></button></form></section></div></div>
}
