const express=require('express');const db=require('../db');const config=require('../config');const {requireAuth}=require('../auth');const {UUID,createToken,encryptToken,hashToken,decryptToken}=require('../nfc');const router=express.Router();
router.use(requireAuth,(req,res,next)=>req.user.role==='admin'?next():res.status(403).json({message:'Administrator access required'}));
router.get('/participants',async(req,res,next)=>{try{const query=String(req.query.q||'').trim().slice(0,100);let request=db.from('participants').select('id,name,email,participant_id,team_id,track,onboarding_completed').order('name').limit(50);if(query){const clean=query.replace(/[,%()]/g,' ');request=request.or(`name.ilike.%${clean}%,email.ilike.%${clean}%,participant_id.ilike.%${clean}%,team_id.ilike.%${clean}%`);}const {data,error}=await request;if(error)throw error;res.json({participants:(data||[]).map(p=>({...p,_id:p.id,participantId:p.participant_id,teamId:p.team_id}))});}catch(error){next(error);}});
router.get('/nfc/tags',async(req,res,next)=>{try{const participantId=req.query.participantId;if(participantId){if(!UUID.test(participantId))return res.status(400).json({message:'A valid participant ID is required'});const result=await db.from('participant_tags').select('id,participant_id,public_token_ciphertext,token_hint,status,assigned_at,revoked_at').eq('participant_id',participantId).eq('status','active').maybeSingle();if(result.error)throw result.error;if(!result.data)return res.json({tag:null});const {public_token_ciphertext,...tag}=result.data;return res.json({tag:{...tag,url:`${config.publicAppUrl}/nfc/t/${decryptToken(public_token_ciphertext)}`}});}const {data,error}=await db.from('participant_tags').select('id,participant_id,token_hint,status,assigned_at,revoked_at').order('assigned_at',{ascending:false}).limit(1000);if(error)throw error;res.json({tags:data||[]});}catch(error){if(/authenticate data|encrypted NFC/i.test(error.message))return res.status(500).json({message:'This badge cannot be recovered with the configured encryption key'});next(error);}});
router.post('/nfc/tags',async(req,res,next)=>{try{const participantId=req.body.participantId;if(!UUID.test(participantId||''))return res.status(400).json({message:'A valid participant ID is required'});const participant=await db.from('participants').select('id,name,participant_id').eq('id',participantId).maybeSingle();if(participant.error)throw participant.error;if(!participant.data)return res.status(404).json({message:'Participant not found'});const active=await db.from('participant_tags').select('id').eq('participant_id',participantId).eq('status','active').maybeSingle();if(active.error)throw active.error;if(active.data)return res.status(409).json({message:'Participant already has an active tag'});const token=createToken();const result=await db.from('participant_tags').insert({participant_id:participantId,public_token_hash:hashToken(token),public_token_ciphertext:encryptToken(token),token_hint:token.slice(-8),assigned_by:req.user.userId}).select('id,token_hint,status,assigned_at').single();if(result.error)throw result.error;res.status(201).json({tag:result.data,participant:participant.data,url:`${config.publicAppUrl}/nfc/t/${token}`,warning:'Program and verify the tag now. This URL remains recoverable by administrators.'});}catch(error){next(error);}});
router.patch('/nfc/tags/:id',async(req,res,next)=>{try{if(!UUID.test(req.params.id)||!['lost','revoked'].includes(req.body.status))return res.status(400).json({message:'A valid tag and revocation reason are required'});const {data,error}=await db.from('participant_tags').update({status:req.body.status,revoked_at:new Date().toISOString()}).eq('id',req.params.id).eq('status','active').select('id,participant_id,token_hint,status,revoked_at').maybeSingle();if(error)throw error;if(!data)return res.status(409).json({message:'This tag is no longer active'});res.json({message:req.body.status==='lost'?'Tag marked lost':'Tag revoked',tag:data});}catch(error){next(error);}});

router.get('/stats',async(_req,res,next)=>{try{const [resources,participants,transactions,tags,pending]=await Promise.all([db.from('resources').select('id,name,category,total_quantity,distributed_quantity'),db.from('participants').select('id',{count:'exact',head:true}),db.from('transactions').select('id',{count:'exact',head:true}),db.from('participant_tags').select('id',{count:'exact',head:true}).eq('status','active'),db.from('submissions').select('id',{count:'exact',head:true}).eq('status','pending')]);const failed=[resources,participants,transactions,tags,pending].find(result=>result.error);if(failed)throw failed.error;const inventory=resources.data||[];res.json({totalParticipants:participants.count||0,totalResources:inventory.length,totalCapacity:inventory.reduce((sum,r)=>sum+(r.total_quantity||0),0),totalDistributed:inventory.reduce((sum,r)=>sum+(r.distributed_quantity||0),0),totalTransactions:transactions.count||0,activeTags:tags.count||0,pendingProofs:pending.count||0,resources:inventory});}catch(error){next(error);}});

router.get('/resources',async(_req,res,next)=>{try{const {data,error}=await db.from('resources').select('*').order('name');if(error)throw error;res.json({resources:data||[]});}catch(error){next(error);}});
router.post('/resources',async(req,res,next)=>{try{const name=String(req.body.name||'').trim().slice(0,100);const category=String(req.body.category||'other').trim().toLowerCase().slice(0,50);const totalQuantity=Number(req.body.totalQuantity);const description=String(req.body.description||'').trim().slice(0,300)||null;if(!name||!Number.isInteger(totalQuantity)||totalQuantity<0||totalQuantity>100000)return res.status(400).json({message:'Name and a valid non-negative quantity are required'});const result=await db.from('resources').insert({name,category,total_quantity:totalQuantity,distributed_quantity:0,description}).select().single();if(result.error)throw result.error;res.status(201).json({message:'Resource created',resource:result.data});}catch(error){next(error);}});
module.exports=router;
