const express=require('express');
const bcrypt=require('bcryptjs');
const db=require('../db');
const {requireAuth,cookieOptions,issueSession}=require('../auth');
const router=express.Router();
const emailOf=value=>String(value||'').trim().toLowerCase();
const participantDto=p=>({userId:p.id,role:'participant',name:p.name,email:p.email,participantId:p.participant_id,teamId:p.team_id,track:p.track,onboardingCompleted:p.onboarding_completed===true,username:p.username,avatarKey:p.avatar_key||'byte'});

router.post('/otp/generate',async(req,res,next)=>{try{const email=emailOf(req.body.email);if(!email)return res.status(400).json({message:'Email is required'});const {data,error}=await db.from('participants').select('id').eq('email',email).maybeSingle();if(error)throw error;if(!data)return res.status(404).json({message:'No registered CodeRed account found with this email'});const {error:otpError}=await db.auth.signInWithOtp({email,options:{shouldCreateUser:true}});if(otpError)throw otpError;res.json({message:'OTP sent to your email'});}catch(error){next(error);}});

router.post('/otp/verify',async(req,res,next)=>{try{const email=emailOf(req.body.email);const otp=String(req.body.otp||'').trim();if(!email||!/^\d{6,8}$/.test(otp))return res.status(400).json({message:'A valid email and 6–8 digit code are required'});const {error:verifyError}=await db.auth.verifyOtp({email,token:otp,type:'email'});if(verifyError)return res.status(401).json({message:'Invalid or expired code'});const {data,error}=await db.from('participants').select('*').eq('email',email).single();if(error||!data)return res.status(404).json({message:'Participant not found'});issueSession(res,{userId:data.id,role:'participant',name:data.name,email});res.json({user:participantDto(data)});}catch(error){next(error);}});

router.post('/staff/login',async(req,res,next)=>{try{const email=emailOf(req.body.email);const password=String(req.body.password||'');const role=req.body.role;if(!['admin','volunteer'].includes(role)||!email||!password)return res.status(400).json({message:'Email, password and a valid staff role are required'});const table=role==='admin'?'admins':'volunteers';const {data,error}=await db.from(table).select('id,name,email,password').eq('email',email).maybeSingle();if(error)throw error;if(!data||!(await bcrypt.compare(password,data.password)))return res.status(401).json({message:'Invalid credentials'});issueSession(res,{userId:data.id,role,name:data.name,email:data.email});res.json({user:{userId:data.id,role,name:data.name,email:data.email}});}catch(error){next(error);}});

router.get('/me',requireAuth,async(req,res,next)=>{try{const table=req.user.role==='participant'?'participants':req.user.role==='volunteer'?'volunteers':req.user.role==='admin'?'admins':null;if(!table)return res.status(401).json({message:'Invalid session role'});const columns=req.user.role==='participant'?'*':'id,name,email';let result=await db.from(table).select(columns).eq('id',req.user.userId).maybeSingle();if(!result.data&&req.user.email)result=await db.from(table).select(columns).eq('email',emailOf(req.user.email)).maybeSingle();if(result.error)throw result.error;if(!result.data)return res.status(404).json({message:'Account no longer exists'});res.json({user:req.user.role==='participant'?participantDto(result.data):{userId:result.data.id,role:req.user.role,name:result.data.name,email:result.data.email}});}catch(error){next(error);}});
router.post('/logout',(_req,res)=>{res.clearCookie('token',cookieOptions());res.json({message:'Logged out'});});
module.exports=router;
