const express=require('express');
const db=require('../db');
const config=require('../config');
const {requireAuth}=require('../auth');
const router=express.Router();
router.use(requireAuth,(req,res,next)=>req.user.role==='participant'?next():res.status(403).json({message:'Participant access required'}));
const fields='id,name,email,participant_id,team_id,track,hall,seat_number,username,bio,github_profile,linkedin_url,portfolio_url,avatar_key,onboarding_completed';
router.get('/me',async(req,res,next)=>{try{const {data,error}=await db.from('participants').select(fields).eq('id',req.user.userId).single();if(error)throw error;res.json({participant:data});}catch(error){next(error);}});
router.patch('/me',async(req,res,next)=>{try{const allowed=['username','bio','github_profile','linkedin_url','portfolio_url','avatar_key'];const changes=Object.fromEntries(allowed.filter(k=>Object.hasOwn(req.body,k)).map(k=>[k,typeof req.body[k]==='string'?req.body[k].trim()||null:req.body[k]]));if(!Object.keys(changes).length)return res.status(400).json({message:'No supported profile fields provided'});if(changes.username&&!/^[a-z0-9-]{3,30}$/.test(changes.username))return res.status(400).json({message:'Username must be 3–30 lowercase letters, numbers, or hyphens'});for(const key of ['github_profile','linkedin_url','portfolio_url'])if(changes[key]&&!isUrl(changes[key]))return res.status(400).json({message:`${key} must be a valid http(s) URL`});changes.onboarding_completed=true;const {data,error}=await db.from('participants').update(changes).eq('id',req.user.userId).select(fields).single();if(error?.code==='23505')return res.status(409).json({message:'That username is already taken'});if(error)throw error;res.json({participant:data});}catch(error){next(error);}});
function isUrl(value){try{return ['http:','https:'].includes(new URL(value).protocol);}catch{return false;}}
router.get('/repository',async(req,res,next)=>{try{const {data,error}=await db.from('participants').select('github_link').eq('id',req.user.userId).single();if(error)throw error;res.json({githubLink:data.github_link||null,submissionsOpen:config.submissionsOpen});}catch(error){next(error);}});
router.put('/repository',async(req,res,next)=>{try{if(!config.submissionsOpen)return res.status(423).json({message:'Project submissions are currently locked'});const parsed=parseGithubRepository(req.body.githubLink);if(!parsed)return res.status(400).json({message:'Enter a GitHub repository URL such as https://github.com/owner/repository'});const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),5000);let response;try{response=await fetch(`https://api.github.com/repos/${encodeURIComponent(parsed.owner)}/${encodeURIComponent(parsed.repo)}`,{headers:{'user-agent':'CodeRed-Portal','accept':'application/vnd.github+json'},signal:controller.signal});}finally{clearTimeout(timeout);}if(response.status===404)return res.status(400).json({message:'Repository is private or does not exist. Only public repositories are accepted'});if(!response.ok)return res.status(503).json({message:'GitHub could not verify this repository. Try again shortly'});const metadata=await response.json();if(metadata.private)return res.status(400).json({message:'Only public repositories are accepted'});const canonical=metadata.html_url;const result=await db.from('participants').update({github_link:canonical,github_access_token:null}).eq('id',req.user.userId).select('id').maybeSingle();if(result.error)throw result.error;if(!result.data)return res.status(404).json({message:'Participant not found'});res.json({message:'Project repository saved',githubLink:canonical});}catch(error){if(error.name==='AbortError')return res.status(503).json({message:'GitHub verification timed out. Try again'});next(error);}});
function parseGithubRepository(value){try{const url=new URL(String(value||'').trim());if(url.protocol!=='https:'||!['github.com','www.github.com'].includes(url.hostname))return null;const parts=url.pathname.split('/').filter(Boolean);if(parts.length!==2)return null;return{owner:parts[0],repo:parts[1].replace(/\.git$/,'')};}catch{return null;}}
module.exports=router;
