const express=require('express');
const multer=require('multer');
const {randomUUID}=require('node:crypto');
const db=require('../db');
const {requireAuth}=require('../auth');
const router=express.Router();
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:2*1024*1024,files:1},fileFilter(_req,file,cb){if(!['image/jpeg','image/png','image/webp'].includes(file.mimetype))return cb(new Error('UNSUPPORTED_IMAGE'));cb(null,true);}});
const participantOnly=(req,res,next)=>req.user.role==='participant'?next():res.status(403).json({message:'Participant access required'});
const staffOnly=(req,res,next)=>['volunteer','admin'].includes(req.user.role)?next():res.status(403).json({message:'Staff access required'});

router.get('/',requireAuth,participantOnly,async(req,res,next)=>{try{const [player,tasks]=await Promise.all([db.from('participants').select('team_id').eq('id',req.user.userId).single(),db.from('tasks').select('*').eq('is_active',true).order('points',{ascending:true})]);if(player.error)throw player.error;if(tasks.error)throw tasks.error;const submissions=player.data.team_id?await db.from('submissions').select('id,task_id,status,proof_url,proof_text,review_note,created_at').eq('team_id',player.data.team_id):{data:[],error:null};if(submissions.error)throw submissions.error;const byTask=new Map((submissions.data||[]).map(s=>[s.task_id,s]));res.json({quests:(tasks.data||[]).map(task=>({...task,submission:byTask.get(task.id)||null}))});}catch(error){next(error);}});

router.post('/submit',requireAuth,participantOnly,upload.single('proof'),async(req,res,next)=>{let proofPath=null;try{const taskId=String(req.body.taskId||'');const proofText=String(req.body.proofText||'').trim().slice(0,500);const [player,task]=await Promise.all([db.from('participants').select('team_id').eq('id',req.user.userId).single(),db.from('tasks').select('id,proof_type,requires_proof,is_active').eq('id',taskId).maybeSingle()]);if(player.error)throw player.error;if(task.error)throw task.error;if(!player.data?.team_id||!task.data?.is_active)return res.status(404).json({message:'Quest or team not found'});if(task.data.requires_proof&&task.data.proof_type==='image'&&!req.file)return res.status(400).json({message:'Add a JPG, PNG, or WebP image under 2 MB'});if(task.data.requires_proof&&task.data.proof_type!=='image'&&!proofText)return res.status(400).json({message:'Add proof before submitting'});if(task.data.proof_type==='link'&&!isUrl(proofText))return res.status(400).json({message:'Enter a valid http(s) proof link'});if(req.file){const extension={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[req.file.mimetype];proofPath=`${player.data.team_id}/${taskId}/${randomUUID()}.${extension}`;const stored=await db.storage.from('quest-proofs').upload(proofPath,req.file.buffer,{contentType:req.file.mimetype,upsert:false});if(stored.error)throw stored.error;}const saved=await db.from('submissions').insert({user_id:req.user.userId,team_id:player.data.team_id,task_id:taskId,proof_url:proofPath,proof_text:proofText||null,status:'pending'});if(saved.error){if(proofPath)await db.storage.from('quest-proofs').remove([proofPath]);if(saved.error.code==='23505')return res.status(409).json({message:'Your team already submitted this quest'});throw saved.error;}res.status(201).json({message:'Proof sent for volunteer review'});}catch(error){if(proofPath)await db.storage.from('quest-proofs').remove([proofPath]);next(error);}});

router.get('/submissions',requireAuth,staffOnly,async(req,res,next)=>{try{const status=['pending','approved','rejected'].includes(req.query.status)?req.query.status:'pending';const result=await db.from('submissions').select('id,user_id,team_id,status,proof_url,proof_text,review_note,created_at,tasks(title,description,points,category)').eq('status',status).order('created_at',{ascending:true}).limit(100);if(result.error)throw result.error;const ids=[...new Set((result.data||[]).map(s=>s.user_id).filter(Boolean))];const people=ids.length?await db.from('participants').select('id,name').in('id',ids):{data:[],error:null};if(people.error)throw people.error;const names=new Map((people.data||[]).map(p=>[p.id,p]));const submissions=await Promise.all((result.data||[]).map(async item=>{let proofImage=null;if(item.proof_url){const signed=await db.storage.from('quest-proofs').createSignedUrl(item.proof_url,300);proofImage=signed.data?.signedUrl||null;}return{...item,participant:names.get(item.user_id)||null,proofImage};}));res.json({submissions});}catch(error){next(error);}});

router.patch('/submissions/:id',requireAuth,staffOnly,async(req,res,next)=>{try{const status=req.body.status;const note=String(req.body.note||'').trim().slice(0,300);if(!['approved','rejected'].includes(status))return res.status(400).json({message:'Invalid review status'});if(status==='rejected'&&!note)return res.status(400).json({message:'Add a reason so the team knows what to fix'});const result=await db.from('submissions').update({status,review_note:note||null,verified_by:req.user.userId,verified_at:new Date().toISOString()}).eq('id',req.params.id).eq('status','pending').select('id').maybeSingle();if(result.error)throw result.error;if(!result.data)return res.status(409).json({message:'This proof was already reviewed'});res.json({message:`Quest ${status}.`});}catch(error){next(error);}});
function isUrl(value){try{return ['http:','https:'].includes(new URL(value).protocol);}catch{return false;}}
module.exports=router;
