const mongoose = require('mongoose');
const User = require('../backend/models/User');
const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '../.env') });

const participants = [
    { team: "4DIRECTION", name: "Aman", track: "CRU", code: "CRU-T01-P01" },
    { team: "4DIRECTION", name: "Bhavya Arora", track: "CRU", code: "CRU-T01-P02" },
    { team: "4DIRECTION", name: "Ponuganti Mahidhar", track: "CRU", code: "CRU-T01-P03" },
    { team: "Caffeine Crew", name: "Thejaswini V Bhat", track: "CRU", code: "CRU-T02-P01" },
    { team: "Caffeine Crew", name: "Chaitra Shree Y S", track: "CRU", code: "CRU-T02-P02" },
    { team: "Caffeine Crew", name: "Sheema Sadiyah Tadipatri", track: "CRU", code: "CRU-T02-P03" },
    { team: "CodeBreaker5", name: "Siddartha N S", track: "CRU", code: "CRU-T03-P01" },
    { team: "CodeBreaker5", name: "Amith S", track: "CRU", code: "CRU-T03-P02" },
    { team: "CodeBreaker5", name: "Hemachandru R", track: "CRU", code: "CRU-T03-P03" },
    { team: "Forbidden Phishers", name: "Shashank Pandey", track: "CRU", code: "CRU-T04-P01" },
    { team: "Forbidden Phishers", name: "Sarthak Patel", track: "CRU", code: "CRU-T04-P02" },
    { team: "Forbidden Phishers", name: "Ankit Singh", track: "CRU", code: "CRU-T04-P03" },
    { team: "GARUDA", name: "SRIJAN U", track: "CRU", code: "CRU-T05-P01" },
    { team: "GARUDA", name: "G BINDUSREE", track: "CRU", code: "CRU-T05-P02" },
    { team: "GARUDA", name: "Tejashwini S Uranakar", track: "CRU", code: "CRU-T05-P03" },
    { team: "Infinity Devs", name: "Sumit Srivastava", track: "CRU", code: "CRU-T06-P01" },
    { team: "Infinity Devs", name: "Dharmit Chauhan", track: "CRU", code: "CRU-T06-P02" },
    { team: "Infinity Devs", name: "Vrushabh Baravkar", track: "CRU", code: "CRU-T06-P03" },
    { team: "INNOVCAMP", name: "NITHIN NAIK.R", track: "CRU", code: "CRU-T07-P01" },
    { team: "INNOVCAMP", name: "PRASAD PATIL", track: "CRU", code: "CRU-T07-P02" },
    { team: "INNOVCAMP", name: "SHIVANAND MANAMI", track: "CRU", code: "CRU-T07-P03" },
    { team: "Kairos", name: "Srinidhi P", track: "CRU", code: "CRU-T08-P01" },
    { team: "Kairos", name: "Madhurya B O", track: "CRU", code: "CRU-T08-P02" },
    { team: "LogiMind", name: "Harshil Sharma", track: "CRU", code: "CRU-T09-P01" },
    { team: "LogiMind", name: "Prakhar singh", track: "CRU", code: "CRU-T09-P02" },
    { team: "LogiMind", name: "Priya T S", track: "CRU", code: "CRU-T09-P03" },
    { team: "LOLgorithms", name: "Sushruth Kumar", track: "CRU", code: "CRU-T10-P01" },
    { team: "LOLgorithms", name: "Srujan S Rao", track: "CRU", code: "CRU-T10-P02" },
    { team: "LOLgorithms", name: "Marudula", track: "CRU", code: "CRU-T10-P03" },
    { team: "Mjolnir", name: "Dheeksha N", track: "CRU", code: "CRU-T11-P01" },
    { team: "Mjolnir", name: "Shashikiran BS", track: "CRU", code: "CRU-T11-P02" },
    { team: "Mjolnir", name: "Pranit Gupta", track: "CRU", code: "CRU-T11-P03" },
    { team: "MSN", name: "Nithin J", track: "CRU", code: "CRU-T12-P01" },
    { team: "MSN", name: "Medha S Harish", track: "CRU", code: "CRU-T12-P02" },
    { team: "NexTech", name: "Chinmayee S Pujar", track: "CRU", code: "CRU-T13-P01" },
    { team: "NexTech", name: "Harinishri R", track: "CRU", code: "CRU-T13-P02" },
    { team: "NexTech", name: "Dhruv Rajwade", track: "CRU", code: "CRU-T13-P03" },
    { team: "No code paradigm", name: "Vinyas G M", track: "CRU", code: "CRU-T14-P01" },
    { team: "No code paradigm", name: "Bhargava Aithal K S", track: "CRU", code: "CRU-T14-P02" },
    { team: "No code paradigm", name: "Ama Shegunasi", track: "CRU", code: "CRU-T14-P03" },
    { team: "Prototype pirates", name: "Nipun Gupta", track: "CRU", code: "CRU-T15-P01" },
    { team: "Prototype pirates", name: "Sameer Jain", track: "CRU", code: "CRU-T15-P02" },
    { team: "Prototype pirates", name: "Kumar vishal", track: "CRU", code: "CRU-T15-P03" },
    { team: "REDBYTE", name: "Mansi Kalgudi", track: "CRU", code: "CRU-T16-P01" },
    { team: "REDBYTE", name: "Shradha Basavaraj Hurakadli", track: "CRU", code: "CRU-T16-P02" },
    { team: "Run Time Terror", name: "Pratyush Visu", track: "CRU", code: "CRU-T17-P01" },
    { team: "Run Time Terror", name: "Aman Raj", track: "CRU", code: "CRU-T17-P02" },
    { team: "Run Time Terror", name: "Ruchi Sao", track: "CRU", code: "CRU-T17-P03" },
    { team: "SlothX", name: "Nuvvula Geethika", track: "CRU", code: "CRU-T18-P01" },
    { team: "SlothX", name: "Lakshmi Sowmya", track: "CRU", code: "CRU-T18-P02" },
    { team: "SlothX", name: "Rafi", track: "CRU", code: "CRU-T18-P03" },
    { team: "Team 0/1", name: "Sunder Gandhi Ningappa", track: "CRU", code: "CRU-T19-P01" },
    { team: "Team 0/1", name: "Tharungowda M Y", track: "CRU", code: "CRU-T19-P02" },
    { team: "Team 269", name: "Keerthi Narayan M V", track: "CRU", code: "CRU-T20-P01" },
    { team: "Team 269", name: "Monish U", track: "CRU", code: "CRU-T20-P02" },
    { team: "Team 269", name: "Arya M", track: "CRU", code: "CRU-T20-P03" },
    { team: "Tech titans", name: "Aditya Kumar bangre", track: "CRU", code: "CRU-T21-P01" },
    { team: "Tech titans", name: "Sneha S Hiremath", track: "CRU", code: "CRU-T21-P02" },
    { team: "Tech titans", name: "Siri U G", track: "CRU", code: "CRU-T21-P03" },
    { team: "TENET", name: "Satvika Prashanth Hiremath", track: "CRU", code: "CRU-T22-P01" },
    { team: "TENET", name: "D Lalith Chandra", track: "CRU", code: "CRU-T22-P02" },
    { team: "TESLA_CURIE", name: "Abhiragini K", track: "CRU", code: "CRU-T23-P01" },
    { team: "TESLA_CURIE", name: "Aditya Mensinkai", track: "CRU", code: "CRU-T23-P02" },
    { team: "TESLA_CURIE", name: "Apeksha Datt", track: "CRU", code: "CRU-T23-P03" },
    { team: "The binary brain", name: "Prajna Saha", track: "CRU", code: "CRU-T24-P01" },
    { team: "The binary brain", name: "Nehal Agarwal", track: "CRU", code: "CRU-T24-P02" },
    { team: "The binary brain", name: "Vaishnavi Chaudhary", track: "CRU", code: "CRU-T24-P03" },
    { team: "THE QUADRENT", name: "MANJULA RANI P N", track: "CRU", code: "CRU-T25-P01" },
    { team: "THE QUADRENT", name: "Shreeraksha Kiran", track: "CRU", code: "CRU-T25-P02" },
    { team: "THE QUADRENT", name: "Shreyas Sathya Prakash", track: "CRU", code: "CRU-T25-P03" },
    { team: "Unified Cargo Exchange(UCX)", name: "V NANDA KISHORE NAIK", track: "CRU", code: "CRU-T26-P01" },
    { team: "Unified Cargo Exchange(UCX)", name: "Pranathi Shetty", track: "CRU", code: "CRU-T26-P02" },
    { team: "Unified Cargo Exchange(UCX)", name: "Paila Divyesh Reddy", track: "CRU", code: "CRU-T26-P03" },
    { team: "Vague_Sense", name: "Amitesh Bhardwaj", track: "CRU", code: "CRU-T27-P01" },
    { team: "Vague_Sense", name: "Kartikeya Verma", track: "CRU", code: "CRU-T27-P02" },
    { team: "Vague_Sense", name: "Aniket Hubballi", track: "CRU", code: "CRU-T27-P03" },
    { team: "APEX-AI-X", name: "Kushal P", track: "CR", code: "CR-T28-P01" },
    { team: "APEX-AI-X", name: "TANISHQ S VERNEKAR", track: "CR", code: "CR-T28-P02" },
    { team: "APEX-AI-X", name: "Yashwanth N", track: "CR", code: "CR-T28-P03" },
    { team: "APEX-AI-X", name: "Rohith G N", track: "CR", code: "CR-T28-P04" },
    { team: "AUTOMATIKS", name: "Sumukh.R", track: "CR", code: "CR-T29-P01" },
    { team: "AUTOMATIKS", name: "Gagan KS", track: "CR", code: "CR-T29-P02" },
    { team: "AUTOMATIKS", name: "Srinidhi P", track: "CR", code: "CR-T29-P03" },
    { team: "AUTOMATIKS", name: "Dayana KM", track: "CR", code: "CR-T29-P04" },
    { team: "BLUE", name: "Dharshan SN", track: "CR", code: "CR-T30-P01" },
    { team: "BLUE", name: "Ananya CV", track: "CR", code: "CR-T30-P02" },
    { team: "BLUE", name: "Nivedita konanavar", track: "CR", code: "CR-T30-P03" },
    { team: "BLUE", name: "Karthik KP", track: "CR", code: "CR-T30-P04" },
    { team: "Brogrammers", name: "Suditya Kulkarni", track: "CR", code: "CR-T31-P01" },
    { team: "Brogrammers", name: "Mallikarjuna M", track: "CR", code: "CR-T31-P02" },
    { team: "Brogrammers", name: "Shubham Prabhu", track: "CR", code: "CR-T31-P03" },
    { team: "Brogrammers", name: "Sujith Kumar", track: "CR", code: "CR-T31-P04" },
    { team: "Chai-Fi", name: "Chethan V", track: "CR", code: "CR-T32-P01" },
    { team: "Chai-Fi", name: "Pavithra B", track: "CR", code: "CR-T32-P02" },
    { team: "Chai-Fi", name: "G Sai Sugeet", track: "CR", code: "CR-T32-P03" },
    { team: "Chai-Fi", name: "Noel David", track: "CR", code: "CR-T32-P04" },
    { team: "Code Wizards", name: "Aakanksha K", track: "CR", code: "CR-T33-P01" },
    { team: "Code Wizards", name: "Nimisha V D", track: "CR", code: "CR-T33-P02" },
    { team: "Code Wizards", name: "Nikhil R", track: "CR", code: "CR-T33-P03" },
    { team: "Code Wizards", name: "V Muhammed Saad Sabeel", track: "CR", code: "CR-T33-P04" },
    { team: "Code Yoddhas", name: "Ishit Barman", track: "CR", code: "CR-T34-P01" },
    { team: "Code Yoddhas", name: "Poorvi M", track: "CR", code: "CR-T34-P02" },
    { team: "Code Yoddhas", name: "Samarth B", track: "CR", code: "CR-T34-P03" },
    { team: "Code Yoddhas", name: "Shreya Krishnan", track: "CR", code: "CR-T34-P04" },
    { team: "CodeOps", name: "V Manivardhan Reddy", track: "CR", code: "CR-T35-P01" },
    { team: "CodeOps", name: "Vivek S M", track: "CR", code: "CR-T35-P02" },
    { team: "CodeOps", name: "Eshwar V", track: "CR", code: "CR-T35-P03" },
    { team: "CodeOps", name: "Yarru Venkata Jaya Krishna", track: "CR", code: "CR-T35-P04" },
    { team: "CodeVortex", name: "Amogh M G", track: "CR", code: "CR-T36-P01" },
    { team: "CodeVortex", name: "Suhana", track: "CR", code: "CR-T36-P02" },
    { team: "CodeVortex", name: "Vikas Annigeri", track: "CR", code: "CR-T36-P03" },
    { team: "CodeVortex", name: "Rohit Yareshimi", track: "CR", code: "CR-T36-P04" },
    { team: "Convoy Command Unit", name: "SHIVANG KAROL", track: "CR", code: "CR-T37-P01" },
    { team: "Convoy Command Unit", name: "PRIYANSHU", track: "CR", code: "CR-T37-P02" },
    { team: "Convoy Command Unit", name: "AGRIM ARORA", track: "CR", code: "CR-T37-P03" },
    { team: "Convoy Command Unit", name: "ADHIRAJ SINGH", track: "CR", code: "CR-T37-P04" },
    { team: "Databaes", name: "Srushti K", track: "CR", code: "CR-T38-P01" },
    { team: "Databaes", name: "Meghana Kiranchand", track: "CR", code: "CR-T38-P02" },
    { team: "Databaes", name: "Sameer kedilaya", track: "CR", code: "CR-T38-P03" },
    { team: "Databaes", name: "Kavana P R", track: "CR", code: "CR-T38-P04" },
    { team: "Databaes", name: "Ayushman sharma", track: "CR", code: "CR-T38-P05" },
    { team: "Databaes", name: "Obana Pujar", track: "CR", code: "CR-T38-P06" },
    { team: "Databaes", name: "Parinitha V", track: "CR", code: "CR-T38-P07" },
    { team: "Databaes", name: "Gayatri P", track: "CR", code: "CR-T38-P08" },
    { team: "Delusion", name: "Samyukthaa M", track: "CR", code: "CR-T39-P01" },
    { team: "Delusion", name: "Sreeya Chand", track: "CR", code: "CR-T39-P02" },
    { team: "Delusion", name: "Prapti", track: "CR", code: "CR-T39-P03" },
    { team: "Delusion", name: "Aniksha Anithan", track: "CR", code: "CR-T39-P04" },
    { team: "Dr Code", name: "Shubham Kumar", track: "CR", code: "CR-T40-P01" },
    { team: "Dr Code", name: "Aditya Sinha", track: "CR", code: "CR-T40-P02" },
    { team: "Dr Code", name: "Mahalakshmi S", track: "CR", code: "CR-T40-P03" },
    { team: "Dr Code", name: "Nishchitha R", track: "CR", code: "CR-T40-P04" },
    { team: "ElectroEdge", name: "ARADHYA PRAKASH", track: "CR", code: "CR-T41-P01" },
    { team: "ElectroEdge", name: "SATYAM KUMAR", track: "CR", code: "CR-T41-P02" },
    { team: "ElectroEdge", name: "ANUPAM PRUSTY", track: "CR", code: "CR-T41-P03" },
    { team: "ElectroEdge", name: "JITAMITRA SAI M", track: "CR", code: "CR-T41-P04" },
    { team: "Electronauts", name: "Pragnya Srikanth Rao", track: "CR", code: "CR-T42-P01" },
    { team: "Electronauts", name: "Prerana Kulkarni", track: "CR", code: "CR-T42-P02" },
    { team: "Electronauts", name: "Stuthi Jansale R", track: "CR", code: "CR-T42-P03" },
    { team: "Electronauts", name: "Manognya Guruprasad", track: "CR", code: "CR-T42-P04" },
    { team: "Forgeon2.0", name: "Nishika R Reddy", track: "CR", code: "CR-T43-P01" },
    { team: "Forgeon2.0", name: "Bhoomika G B", track: "CR", code: "CR-T43-P02" },
    { team: "Forgeon2.0", name: "Akansha Kumari", track: "CR", code: "CR-T43-P03" },
    { team: "FourLoop", name: "Kshitiz Khandelwal", track: "CR", code: "CR-T44-P01" },
    { team: "FourLoop", name: "Harsh Jha", track: "CR", code: "CR-T44-P02" },
    { team: "FourLoop", name: "Priyanshi Gupta", track: "CR", code: "CR-T44-P03" },
    { team: "FourLoop", name: "Muskan Singh", track: "CR", code: "CR-T44-P04" },
    { team: "Full Stack Biryani", name: "Tanmay Sachin Kapadnis", track: "CR", code: "CR-T45-P01" },
    { team: "Full Stack Biryani", name: "Shambhavi Manjunath", track: "CR", code: "CR-T45-P02" },
    { team: "Full Stack Biryani", name: "Sunisha P S", track: "CR", code: "CR-T45-P03" },
    { team: "Full Stack Biryani", name: "Pranay Raj Singh", track: "CR", code: "CR-T45-P04" },
    { team: "GENESIS", name: "HEMANTH S", track: "CR", code: "CR-T46-P01" },
    { team: "GENESIS", name: "Sumadhwa V", track: "CR", code: "CR-T46-P02" },
    { team: "GENESIS", name: "Suman GS", track: "CR", code: "CR-T46-P03" },
    { team: "GENESIS", name: "Ajay D Bhat", track: "CR", code: "CR-T46-P04" },
    { team: "Half Brain Cell", name: "Varsha Lakshmi K", track: "CR", code: "CR-T47-P01" },
    { team: "Half Brain Cell", name: "Keerthana R Nair", track: "CR", code: "CR-T47-P02" },
    { team: "Half Brain Cell", name: "Chinmay G C", track: "CR", code: "CR-T47-P03" },
    { team: "Half Brain Cell", name: "Prithveesh Rao", track: "CR", code: "CR-T47-P04" },
    { team: "Hardkode3.0", name: "Abhay Krishna B", track: "CR", code: "CR-T48-P01" },
    { team: "Hardkode3.0", name: "Mohith K Aralikatte", track: "CR", code: "CR-T48-P02" },
    { team: "Hardkode3.0", name: "Soumyadeep Mukherjee", track: "CR", code: "CR-T48-P03" },
    { team: "Hardkode3.0", name: "Chinmay Ravindra gowda", track: "CR", code: "CR-T48-P04" },
    { team: "Invincible_4", name: "MD UMAR ABDULLAH", track: "CR", code: "CR-T49-P01" },
    { team: "Invincible_4", name: "MD.SAFWAN ANSARI", track: "CR", code: "CR-T49-P02" },
    { team: "Invincible_4", name: "Abdul hannan", track: "CR", code: "CR-T49-P03" },
    { team: "Invincible_4", name: "Aayan Asif", track: "CR", code: "CR-T49-P04" },
    { team: "KAFKA", name: "Shivani N K", track: "CR", code: "CR-T50-P01" },
    { team: "KAFKA", name: "Bhumika", track: "CR", code: "CR-T50-P02" },
    { team: "KAFKA", name: "Dishaka Y bhat", track: "CR", code: "CR-T50-P03" },
    { team: "KAFKA", name: "Likitha S A", track: "CR", code: "CR-T50-P04" },
    { team: "Kronyx", name: "Vaibhav M N", track: "CR", code: "CR-T51-P01" },
    { team: "Kronyx", name: "Yashas Manju Urs", track: "CR", code: "CR-T51-P02" },
    { team: "Kronyx", name: "Aneesh Aveen Sunganahalli", track: "CR", code: "CR-T51-P03" },
    { team: "Kronyx", name: "Anirudh Kashyap", track: "CR", code: "CR-T51-P04" },
    { team: "LogicHigh", name: "Keerthan A K", track: "CR", code: "CR-T52-P01" },
    { team: "LogicHigh", name: "Pramod Urs O", track: "CR", code: "CR-T52-P02" },
    { team: "LogicHigh", name: "Sagar Anil Shigehalli", track: "CR", code: "CR-T52-P03" },
    { team: "MisaMisa", name: "Mohit V S", track: "CR", code: "CR-T53-P01" },
    { team: "MisaMisa", name: "Aaryan Rao", track: "CR", code: "CR-T53-P02" },
    { team: "MisaMisa", name: "Adith Senthil", track: "CR", code: "CR-T53-P03" },
    { team: "MisaMisa", name: "Anoop Ganesh", track: "CR", code: "CR-T53-P04" },
    { team: "Momentum Crew", name: "Neeraja R", track: "CR", code: "CR-T54-P01" },
    { team: "Momentum Crew", name: "Spandana", track: "CR", code: "CR-T54-P02" },
    { team: "Momentum Crew", name: "Prathibha", track: "CR", code: "CR-T54-P03" },
    { team: "Neural Net Ninjas", name: "Sarang Sanjay", track: "CR", code: "CR-T55-P01" },
    { team: "Neural Net Ninjas", name: "Suhas Shivakumar", track: "CR", code: "CR-T55-P02" },
    { team: "Neural Net Ninjas", name: "Bhuvan Gowda N C", track: "CR", code: "CR-T55-P03" },
    { team: "Neural Nooks", name: "S Srinidhi VAS", track: "CR", code: "CR-T56-P01" },
    { team: "Neural Nooks", name: "Kotturesh Vybhav", track: "CR", code: "CR-T56-P02" },
    { team: "Neural Nooks", name: "Arkesh.N", track: "CR", code: "CR-T56-P03" },
    { team: "Neural Nooks", name: "Dhanush.P", track: "CR", code: "CR-T56-P04" },
    { team: "NextGen", name: "Dayana B", track: "CR", code: "CR-T57-P01" },
    { team: "NextGen", name: "K Y K Govardhana", track: "CR", code: "CR-T57-P02" },
    { team: "NextGen", name: "Manushree DV", track: "CR", code: "CR-T57-P03" },
    { team: "NextGen", name: "Harish Kumar V", track: "CR", code: "CR-T57-P04" },
    { team: "Phishfry", name: "Harshita Nagesh", track: "CR", code: "CR-T59-P01" },
    { team: "Phishfry", name: "Rayyan Shaikh", track: "CR", code: "CR-T59-P02" },
    { team: "Phishfry", name: "Ashitha Patil", track: "CR", code: "CR-T59-P03" },
    { team: "QuadraBytes", name: "Supreetha M", track: "CR", code: "CR-T60-P01" },
    { team: "QuadraBytes", name: "Neha M Kudur", track: "CR", code: "CR-T60-P02" },
    { team: "QuadraBytes", name: "Pavani GK", track: "CR", code: "CR-T60-P03" },
    { team: "QuadraBytes", name: "Joyal John Mangatt", track: "CR", code: "CR-T60-P04" },
    { team: "Questers", name: "Surabhi R Nadig", track: "CR", code: "CR-T61-P01" },
    { team: "Questers", name: "Sanjana Shanbhag", track: "CR", code: "CR-T61-P02" },
    { team: "Questers", name: "Tara Panth", track: "CR", code: "CR-T61-P03" },
    { team: "Questers", name: "Swati B Mathapati", track: "CR", code: "CR-T61-P04" },
    { team: "Reboot", name: "Aishwarya JA", track: "CR", code: "CR-T62-P01" },
    { team: "Reboot", name: "Ananya Dinesh", track: "CR", code: "CR-T62-P02" },
    { team: "Reboot", name: "Neha Gujjar", track: "CR", code: "CR-T62-P03" },
    { team: "Reboot", name: "Abdullah", track: "CR", code: "CR-T62-P04" },
    { team: "Runtime Terrors", name: "Harshendra M", track: "CR", code: "CR-T63-P01" },
    { team: "Runtime Terrors", name: "Shashwath Prabhu", track: "CR", code: "CR-T63-P02" },
    { team: "Runtime Terrors", name: "Shivesh Tiwari", track: "CR", code: "CR-T63-P03" },
    { team: "Runtime Terrors", name: "Swapnil Rao", track: "CR", code: "CR-T63-P04" },
    { team: "Tech Titans", name: "POORVI M SURESH", track: "CR", code: "CR-T64-P01" },
    { team: "Tech Titans", name: "VISHNUSHREE R", track: "CR", code: "CR-T64-P02" },
    { team: "Tech Titans", name: "DIGVIJAY PATIL", track: "CR", code: "CR-T64-P03" },
    { team: "Tech Titans", name: "Rahul Kumar Gupta", track: "CR", code: "CR-T64-P04" },
    { team: "The Gradient Decendents", name: "Mehaboob S", track: "CR", code: "CR-T65-P01" },
    { team: "The Gradient Decendents", name: "Yashwanth BL", track: "CR", code: "CR-T65-P02" },
    { team: "The Gradient Decendents", name: "Rahul R Vasisht", track: "CR", code: "CR-T65-P03" },
    { team: "Titan Core", name: "Aashish Thakur", track: "CR", code: "CR-T66-P01" },
    { team: "Titan Core", name: "Akshat Kumar Tiwary", track: "CR", code: "CR-T66-P02" },
    { team: "Titan Core", name: "Lakshy lohar", track: "CR", code: "CR-T66-P03" },
    { team: "Titan Core", name: "Bhanuprakash", track: "CR", code: "CR-T66-P04" },
    { team: "Tryanuka", name: "Tejas H J", track: "CR", code: "CR-T67-P01" },
    { team: "Tryanuka", name: "Abhishek Rao k", track: "CR", code: "CR-T67-P02" },
    { team: "Tryanuka", name: "Havyas M P", track: "CR", code: "CR-T67-P03" },
    { team: "VCPRO", name: "Samarth Singh", track: "CR", code: "CR-T68-P01" },
    { team: "VCPRO", name: "Shlok Saitavya", track: "CR", code: "CR-T68-P02" },
    { team: "VCPRO", name: "Aditya Rai", track: "CR", code: "CR-T68-P03" },
    { team: "VCPRO", name: "Prithvi Aparna", track: "CR", code: "CR-T68-P04" },
    { team: "VELOCITY FLYERS", name: "Shreyas S N", track: "CR", code: "CR-T69-P01" },
    { team: "VELOCITY FLYERS", name: "GAURAV I K", track: "CR", code: "CR-T69-P02" },
    { team: "VELOCITY FLYERS", name: "Drupadsurya", track: "CR", code: "CR-T69-P03" },
    { team: "VELOCITY FLYERS", name: "Sri Murari", track: "CR", code: "CR-T69-P04" },
    { team: "Vision Vortex", name: "Bhuvan K K", track: "CR", code: "CR-T70-P01" },
    { team: "Vision Vortex", name: "Avyaya S Yekkar", track: "CR", code: "CR-T70-P02" },
    { team: "Vision Vortex", name: "Shreyank D K", track: "CR", code: "CR-T70-P03" },
    { team: "Vision Vortex", name: "N R Mahesh Raju", track: "CR", code: "CR-T70-P04" },
    { team: "VITACORE AI", name: "POORVI M", track: "CR", code: "CR-T71-P01" },
    { team: "VITACORE AI", name: "UMME HAFSA", track: "CR", code: "CR-T71-P02" },
    { team: "VITACORE AI", name: "ZOHA TABASSUM KHADER", track: "CR", code: "CR-T71-P03" },
    { team: "VITACORE AI", name: "HARSHITHA M", track: "CR", code: "CR-T71-P04" },
    { team: "Wi - Fight club", name: "Abhilash G", track: "CR", code: "CR-T72-P01" },
    { team: "Wi - Fight club", name: "Abhinav C", track: "CR", code: "CR-T72-P02" },
    { team: "Wi - Fight club", name: "Ashrith Srivathsa KS", track: "CR", code: "CR-T72-P03" },
    { team: "Wi - Fight club", name: "Ajay Kumar R", track: "CR", code: "CR-T72-P04" },
    { team: "WI-FIGTERS", name: "Shreyank prabhu CB", track: "CR", code: "CR-T73-P01" },
    { team: "WI-FIGTERS", name: "Ramya B J", track: "CR", code: "CR-T73-P02" },
    { team: "WI-FIGTERS", name: "Swati karnalkar", track: "CR", code: "CR-T73-P03" },
    { team: "WI-FIGTERS", name: "Suma Sunar", track: "CR", code: "CR-T73-P04" },
    { team: "WISH", name: "Wamika Varada", track: "CR", code: "CR-T74-P01" },
    { team: "WISH", name: "Pratyusha Suresh", track: "CR", code: "CR-T74-P02" },
    { team: "WISH", name: "Sahana S", track: "CR", code: "CR-T74-P03" },
    { team: "Material Girlz", name: "Nishika", track: "CRU", code: "CRU-T75-P01" },
    { team: "Material Girlz", name: "Parvathy C", track: "CRU", code: "CRU-T75-P02" },
    { team: "Material Girlz", name: "Shreeya", track: "CRU", code: "CRU-T75-P03" },
    { team: "Signotech", name: "Aryan R", track: "CR", code: "CR-T76-P01" },
    { team: "Signotech", name: "B Suraj", track: "CR", code: "CR-T76-P02" },
    { team: "Signotech", name: "Gurudatt N", track: "CR", code: "CR-T76-P03" },
    { team: "Signotech", name: "P Achyuth", track: "CR", code: "CR-T76-P04" },
    { team: "TEAM INFRARED", name: "Jiya Kulkarni", track: "CR", code: "CR-T77-P01" },
    { team: "TEAM INFRARED", name: "M Poojashri", track: "CR", code: "CR-T77-P02" },
    { team: "TEAM INFRARED", name: "Mandar Joshi", track: "CR", code: "CR-T77-P03" },
    { team: "TEAM INFRARED", name: "Manjunatha", track: "CR", code: "CR-T77-P04" },
];

const seedParticipants = async () => {
    try {
        await mongoose.connect(process.env.MONGODB_URI);
        console.log('Connected to MongoDB');

        // Optional: Clear existing participants if needed (be careful!)
        // await User.deleteMany({ role: 'participant' });

        // Drop indexes to ensure sparse index on email is applied (since we are changing from required unique to sparse unique)
        try {
            await User.collection.dropIndexes();
            console.log('Indexes dropped');
        } catch (e) {
            console.log('No indexes to drop or drop failed:', e.message);
        }

        for (const user of participants) {
            // Check if user already exists
            const existingUser = await User.findOne({ qrCode: user.code });
            if (!existingUser) {
                await User.create({
                    name: user.name,
                    teamId: user.team,
                    qrCode: user.code,
                    role: 'participant',
                    track: user.track,
                    // No email or password
                });
                console.log(`Added ${user.name} (${user.code})`);
            } else {
                console.log(`Skipped ${user.name} (${user.code}) - Already exists`);
            }
        }

        console.log('Seeding completed');
        mongoose.connection.close();
    } catch (error) {
        console.error('Seeding failed:', error);
        process.exit(1);
    }
};

seedParticipants();
