'use client'
import { useEffect, useState } from 'react'
import { Check, Clock3, ExternalLink, RefreshCw, ShieldCheck, X } from 'lucide-react'
export default function QuestReviewPage() {
  const [items, setItems] = useState<any[]>([]); const [busy, setBusy] = useState(''); const [note, setNote] = useState<Record<string,string>>({}); const [error,setError]=useState(''); const [loading,setLoading]=useState(true)
  const load = () => {setLoading(true);setError('');fetch('/api/volunteers/quest-submissions?status=pending').then(async(r)=>{const d=await r.json();if(!r.ok)throw new Error(d.message);setItems(d.submissions||[])}).catch((e)=>setError(e.message||'Could not load proofs.')).finally(()=>setLoading(false))}; useEffect(load, [])
  async function review(id: string, status: string) { setBusy(id); setError(''); const response = await fetch(`/api/volunteers/quest-submissions/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ status, note: note[id] }) }); const data=await response.json(); setBusy(''); if (response.ok) setItems((current) => current.filter((item) => item.id !== id)); else setError(data.message||'Review failed.') }
  return <div className="game-stack"><div className="page-heading"><div><p className="eyebrow">GUILD DESK</p><h1>Quest verification</h1><p>Oldest proofs appear first. Open links and images before awarding XP.</p></div><button className="pixel-button secondary" onClick={load}><RefreshCw/> REFRESH</button></div>{error&&<p className="game-error">{error}</p>}<div className="review-grid">{items.map((item) => <article className="pixel-panel review-card" key={item.id}><div className="review-head"><span><Clock3/> WAITING</span><b>+{item.tasks?.points} XP</b></div><h2>{item.tasks?.title}</h2><p>{item.tasks?.description}</p><div className="review-team"><ShieldCheck/><span><small>TEAM</small><b>{item.team_id}</b></span><span><small>SUBMITTED BY</small><b>{item.participants?.name || 'Participant'}</b></span></div>{item.proofImage && <a className="proof-image" href={item.proofImage} target="_blank" rel="noreferrer"><img src={item.proofImage} alt="Quest proof"/><span><ExternalLink/> OPEN FULL PROOF</span></a>}{item.proof_text && <a className="text-proof" href={item.proof_text.startsWith('http') ? item.proof_text : undefined} target="_blank" rel="noreferrer">{item.proof_text}{item.proof_text.startsWith('http') && <ExternalLink/>}</a>}<textarea className="review-note" value={note[item.id] || ''} onChange={(e) => setNote((n) => ({ ...n, [item.id]: e.target.value }))} placeholder="Optional note (required if rejecting)"/><div className="review-actions"><button disabled={busy === item.id} onClick={() => review(item.id, 'rejected')}><X/> REJECT</button><button disabled={busy === item.id} onClick={() => review(item.id, 'approved')}><Check/> AWARD XP</button></div></article>)}{!loading&&!error&&!items.length && <div className="pixel-panel empty-game"><Check/><b>QUEUE CLEARED</b><p>No proofs are waiting for review.</p></div>}{loading&&<div className="pixel-panel empty-game"><RefreshCw className="spin"/><b>LOADING PROOFS...</b></div>}</div></div>
}
